apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: springboot-demo
  name: springboot-demo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: springboot-demo
    spec:
      containers:
      - image: springboot
        name: springboot-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        resources: {}
      # restartPolicy: Always
status: {}
